app {
  http {
    host = ${HTTP_HOST}
    port = ${HTTP_PORT}
    timeout = 40 seconds
  }
  
  one-frame {
    url = ${ONEFRAME_URL}
    token = ${ONEFRAME_TOKEN}
    time-tolerance = ${ONEFRAME_TIME_TOLERANCE}
  }
  
  cache {
    ttl = ${CACHE_TTL}
  }
}

